defaults:
  - data: sudoku
  - _self_

arch:
  name: rt@RecurrentTransformer

  # Transformer
  num_layers: 4

  hidden_size: 512
  intermediate_size: 2048
  head_dim: 64

  norm_eps: 1e-6
  rope_theta: 10000.0

  # HRM
  cycles: 7
  bptt: True

  forward_dtype: bfloat16

seeds: [1, 2, 3]

cycles_per_data: 16
epochs: 20

local_batch_size: 96

lr: 1e-4
lr_warmup_steps: 2000
lr_min_ratio: 1.0

beta1: 0.9
beta2: 0.95
weight_decay: 1.0
ema: 0.999
